# Generated by Django 5.2 on 2025-05-14 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('codigo_producto', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tipo_producto', models.CharField(choices=[('calzado', 'Calzado'), ('ropa', 'Ropa'), ('deporte', 'Deportes'), ('lociones', 'Lociones'), ('llaveros', 'Llaveros'), ('vasos', 'Vasos'), ('varios', 'Varios')], max_length=10)),
                ('talla', models.CharField(max_length=5)),
                ('color', models.CharField(choices=[('Rojo', 'rojo'), ('Azul', 'azul'), ('Verde', 'verde'), ('Morado', 'morado'), ('Negro', 'negro'), ('Beige', 'beige'), ('Cafe', 'cafe'), ('Celeste', 'celeste'), ('Blanco', 'blanco')], max_length=10)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.inventario')),
            ],
        ),
    ]
