# Generated by Django 5.2 on 2025-05-14 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuario.usuario')),
                ('codigo', models.CharField(max_length=10)),
                ('fecha_cobro', models.DateField()),
            ],
        ),
    ]
