# Generated by Django 5.2 on 2025-05-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('identidad', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=50, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('contrasenia', models.CharField(max_length=50)),
            ],
        ),
    ]
