# Generated by Django 5.2 on 2025-05-14 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
        ('proveedor', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del pago')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de pago')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque')], default='EFECTIVO', max_length=20, verbose_name='Método de pago')),
                ('referencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de referencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_credito', to='usuario.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PagoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del pago')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de pago')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque')], default='EFECTIVO', max_length=20, verbose_name='Método de pago')),
                ('referencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de referencia')),
                ('concepto_nomina', models.CharField(max_length=100, verbose_name='Concepto de nómina')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_empleado', to='empleado.empleado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PagoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del pago')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de pago')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque')], default='EFECTIVO', max_length=20, verbose_name='Método de pago')),
                ('referencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de referencia')),
                ('factura', models.CharField(max_length=20, verbose_name='Número de factura')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='IVA aplicado')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_proveedor', to='proveedor.proveedor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
