# Generated by Django 5.2 on 2025-05-14 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuario.usuario')),
                ('codigo_empleado', models.CharField(max_length=15, unique=True)),
                ('fecha_contrato', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField()),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.rol')),
            ],
        ),
    ]
